### ISSUE TITLE
How does it actually work?

### ISSUE THREAD

**Issue by engrun** [willemsrb/sonar-jdepend-plugin#1] opened 2016-11-29 10:13 UTC
Hi

Very interested in this plugin, so great initiativ!
But I'm a bit confused how this actually work. 

Does it import an existing xml from a jdepend analysis?

Also not sure about being forced to having a package-info.java in every package?
We have a large codebase and it really is not viable to have this package-info.java in each and every package. 

So this "issue" is basically a request to improve the documentation

**Comment by willemsrb** [comment] 2016-11-29 14:48
Hi Rune,

thank you for your message!

This plug-in actually contains the Jdepend library and executes it as a
part of the execution of the SonarQube sensor.
So you don't have to change anything in your existing builds to add the
functionality.
It cannot import an existing XML, i could make that possible in a future
version, but i would have to read up on the XML
format that Jdepend uses.

The package-info.java is the file the issues are connected too. In
SonarQube it is not possible (as far as i know) to have
an issue on anything else than an existing file, so i had to make a choice
between either adding it to a random class in
the package or adding it to a pre-defined place (the package-info.java) and
'forcing' that requirement.
If you have a suggestion how to add the issues to a logical place without
it being pre-defined, but still working in a
logical way, i would be delighted.

I'll also add the information in the documentation!

Regards,
Robert

**Comment by engrun** [comment] 2016-11-30 09:59
Hi, thanks for the informative reply.
I have added the plugin to our Sonar installation, and the JDepend is now listed under "Measures"
All good.
However, the missing-package-info rule reports 474 packages. 
For a greenfield application enforcing the package-info.java file is viable, but for a larger existing codebase this perhaps is not the best idea. I see the downsides to connecting this information to a random class (what happends if the class is deleted?), but for existing codebases this is perhaps a better solution (at least shortterm?)

Idea:
Can the plugin generate a dummy file in each package before analysis and then delete the file after the analysis is done?

And can the package-info vs random class be configurable?

regards

**Comment by engrun** [comment] 2016-11-30 10:02
Anyway, I'll look into writing a script that generates the package-info.java file if missing. 

Can this file be empty?

**Comment by willemsrb** [comment] 2016-12-02 17:17
Hi Rune,

i looked at your idea, as i was intrigued by it. but unfortunately the
SonarQube filesystem interface does not support that.
I'll investigate it further as adding a 'virtual' file is something i would
fancy.

For the next version i'll make the package-info vs random class
configurable. It is a little much to add that in this version.

Regards,
Robert

**Comment by willemsrb** [comment] 2016-12-02 17:18
The package-info.java cannot be empty. It should contain at least one line
containing the package definition. Eg:

package nl.futureedge.sub.sub.sub;

Regards,
Robert

**Comment by engrun** [comment] 2016-12-05 08:13
FYI. I have created a groovy script that traverses packages and creates the missing package-info.java files. 
After this the "Missing package-info files" has dropped to 47 (from 474). 
However, afferent, efferent and package cycles still report 0. 
Not sure how to debug this

**Comment by willemsrb** [comment] 2016-12-05 08:49
Hi Rune,

good going! Could you show me the structure of the packages/classes you are
expecting the afferents, efferents and cycles on? Then i can try to
reproduce the situation.

Regards,
Robert

**Comment by engrun** [comment] 2016-12-05 09:10
http://tinypic.com/r/rtp9n4/9

I have uploaded an image displaying output from jdepend (when run manually). 
Is this of any help?

**Comment by engrun** [comment] 2016-12-12 08:50
Any news on this?

**Comment by willemsrb** [comment] 2016-12-14 06:19
Hi Rune,

at this moment i do not have any progress on a new version. (Unfortunately
i've been sick).
My plans however are to add the package cycles to the classes that
introduce them. It seems a better option than adding them to a random class.
I'm currently looking at the jdepend fork as it already does this in the
reports; haven't had much time though

Regards,
Robert

**Comment by engrun** [comment] 2016-12-16 07:53
Totally understand. 
My question was more related to afferent/efferent coupling not showing. Meanwhile I'll stick to using the command line tool :)

**Comment by archonwang** [comment] 2017-02-24 03:43
HI，@willemsrb
I have a question about the  plugin, Could it support other language such as c#, php or others besides java? Thanks.

**Comment by SebastianDietrich** [comment] 2017-03-21 09:01
@engrun - could you please post that script?
@willemsrb maybe you could add it to some tools directory and reference it from the documentation?

**Comment by engrun** [comment] 2017-03-24 08:08
@SebastianDietrich 

Copy-paste of script code 

```
import static groovy.io.FileType.*
import static groovy.io.FileVisitResult.*

def srcDirs = [
        new File('./submodule1/src/main/java/no/tine'),

        new File('./submodule2/api/src/main/java/no/tine')
]

srcDirs.each() {

    def createPackageInfo = {
        if (hasFiles(it)) {
            File info = new File(it, 'package-info.java')
            String packageName = it.getCanonicalPath().split('src/main/java').last().replace('/', '.').replaceFirst('.', '')
            if (!info.exists()) {
                info.createNewFile()
                info << "package ${packageName};"
            }
        }
    }


    def countFilesAndDirs = 0
    it.traverse {
        countFilesAndDirs++
    }
    println "Total files and directories in ${it.name}: $countFilesAndDirs"

    it.traverse type: DIRECTORIES, visit: createPackageInfo
}

def hasFiles(File file) {
    def isEmpty = file.listFiles().find {
        if ( it.isFile() && !it.getName().equals('.DS_Store') ) {
            return true
        }
    }
    return isEmpty
}
```

Use at your own risk ;)

**Comment by willemsrb** [comment] 2017-04-21 21:59
All,
i've started a new plugin that addresses all issues (https://github.com/willemsrb/sonar-packageanalyzer-plugin). It is not based on the jDepend plugin but replicates (almost) all rules. Because i can now use a different model the issues can be registered on other places than only the package-info.java file. The seperation of model, rules and source code loading it can also support other languages than Java (it only supports Java currently). I've also included a little package-info.java generator (java based, not groovy).

The new plugin is still a little rough and not fully completed; however i invite you to have a look and see if it adresses the issues in a way you like.

Regards,
Robert

**Comment by engrun** [comment] 2017-04-26 07:45
Hi. I'll check it out later. The new plugin requires Sonar 6.3, so I have to wait for the scheduled update of our Sonar instance.

**Comment by nargxf-zz** [comment] 2017-06-01 12:25
Hi, I've installed JDepend plugin with SONAR v5.6. I've created the package-info.java files however I don't get any results. Do I have to configure something more?

Thank you in advance
Nikos

**Comment by willemsrb** [comment] 2017-06-01 15:00
Hi Nikos,

Yes, you need to activate the rules to get results.

Regards,
Robert

**Comment by nargxf-zz** [comment] 2017-06-02 06:08
I can't see any rules relative to jdepend somewhere to activate.

**Comment by willemsrb** [comment] 2017-06-03 07:52
Do you have the Sonarqube Java Plugin installed? The rules are coupled to
the Java language.

Op 2 jun. 2017 8:08 a.m. schreef "Nikos Argyriou" <notifications@github.com
>:

I can't see any rules relative to jdepend somewhere to activate.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/willemsrb/sonar-jdepend-plugin/issues/1#issuecomment-305698479>,
or mute the thread

**Comment by nargxf-zz** [comment] 2017-06-06 06:34
I has the SonarWay ruleset for Java installed. However, I can't find these rules. I've searched with the JDepend keyword but nothing. What am I looking for?

**Comment by willemsrb** [comment] 2017-07-07 10:04
![sonarqube](https://user-images.githubusercontent.com/8638456/27953515-68c3a3fa-630c-11e7-9539-485c5ae2e924.png)

It should show up like this.

**Comment by willemsrb** [comment] 2017-07-07 11:12
Closing this issue as it has turned a general thread.

**Closed as completed by willemsrb** 2017-07-07 11:12 UTC
